spring:
  application:
    name: bankramen-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secretKey: ${JWT_SECRET}
  header: ${HEADER}
  prefix: ${PREFIX}
  accessExp: ${ACCESS_EXP}

springdoc:
  api-docs:
    path: ${API_DOCS_PATH}

  swagger-ui:
    path: ${SWAGGER_UI_PATH}
    operations-sorter: method # method(HTTP METHOD 순 정렬), alpha(알파벳 순 정렬)
    tags-sorter: alpha # method(HTTP METHOD 순 정렬), alpha(알파벳 순 정렬)
    display-request-duration: true
    try-it-out-enabled: true
    doc-expansion: none # none(전부 접힘), list(목록만 펼침), full(전부 펼침)
    persist-authorization: true

  default-consumes-media-type: application/json
  default-produces-media-type: application/json